default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dodo_library_development

test:
  <<: *default
  database: dodo_library_test

production:
  <<: *default
  database: dodo_library_production
  username: dodo_library
  password: <%= ENV['DODO_LIBRARY_DATABASE_PASSWORD'] %>
